change loopCnt increase local
adafruit/Adafruit_SHT31 pull request #28
Opened 2020-07-21 18:46 UTC by welvins

The increment inside the argument if, if (++loopCnt == 30), does not work in every IDE, e. g., Arduino IDE 1.8.10. I just moved it to another area of ​​the loop

Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

2020-07-21 18:47 UTC, ladyada approved these changes

2022-02-20 23:37 UTC, dhalbert requested changes
This PR never got merged, because the build got stuck. Making some minor changes to get it to run again.

2022-02-20 23:37 UTC, dhalbert commented on examples/SHT31test/SHT31test.ino
> +  if (loopCnt == 30) {
for safety
```suggestion
  if (loopCnt >= 30) {
```

2022-02-20 23:37 UTC, dhalbert commented on examples/SHT31test/SHT31test.ino
> +  loopCnt = loopCnt+1;
simplicity
```suggestion
  loopCnt++;
```

2022-02-21 00:47 UTC, ladyada approved these changes

2022-02-21 00:47 UTC, merged